# Generated by Django 5.0.1 on 2024-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover_photo"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pictures"
            ),
        ),
    ]
